sudo: required
services:
  - docker

before_install:
  - docker build -t lukasjvdm/react-test -f ./client/Dockerfile.dev ./client
  #-docker build myotherproject     -> if we want to add more tests for server/worker

script:
  - docker run lukasjvdm/react-test npm test -- --coverage #the tag ensures that the test suite actually exits after completion with its appropriate code
  #-docker run myother project runmytests

after_success:
  - docker build -t lukasjvdm/multi-client ./client
  - docker build -t lukasjvdm/multi-nginx ./nginx
  - docker build -t lukasjvdm/multi-server ./server
  - docker build -t lukasjvdm/multi-worker ./worker

  